export const YEAR_OPTIONS = [
  '1st Year',
  '2nd Year',
  '3rd Year',
  '4th Year',
  '5th Year',
  '6th Year',
  'Passed Out / Alumni',
  'Working Professional',
];

export const SUBJECT_CATALOG = {
  'School Subjects': [
    'Mathematics',
    'Physics',
    'Chemistry',
    'Biology',
    'English',
    'Hindi',
    'History',
    'Geography',
    'Political Science',
    'Economics',
    'Accountancy',
    'Business Studies',
    'Computer Science',
    'Physical Education',
    'Sanskrit',
    'Sociology',
    'Psychology',
    'Fine Arts',
    'Music',
    'Home Science',
    'Civics',
    'Environmental Science',
  ],
  'College Courses': [
    'BTech Computer Science',
    'BTech Electronics',
    'BTech Mechanical',
    'BTech Civil',
    'BTech IT',
    'BE',
    'BSc Physics',
    'BSc Chemistry',
    'BSc Mathematics',
    'BSc Biology',
    'BSc Computer Science',
    'BCA',
    'BSc Biotechnology',
    'BSc Agriculture',
    'BSc Nursing',
    'MBBS',
    'BDS',
    'BPharm',
    'BAMS',
    'BHMS',
    'BBA',
    'BBM',
    'BCom',
    'BCom Honours',
    'CA Foundation',
    'CA Intermediate',
    'CA Final',
    'CS Foundation',
    'CMA Foundation',
    'MBA',
    'PGDM',
    'BA English',
    'BA Hindi',
    'BA History',
    'BA Geography',
    'BA Political Science',
    'BA Sociology',
    'BA Psychology',
    'BA Economics',
    'BA Journalism',
    'BA Mass Communication',
    'BFA',
    'BJMC',
    'LLB',
    'LLM',
    'BArch',
    'BDes',
    'BHM',
    'BEd',
    'Polytechnic Diploma',
    'ANM',
    'GNM Nursing',
    'BVSc',
  ],
  'Engineering Entrance': [
    'JEE Main',
    'JEE Advanced',
    'BITSAT',
    'VITEEE',
    'SRMJEEE',
    'MHT-CET',
    'AP EAMCET',
    'TS EAMCET',
    'KEAM',
    'WBJEE',
    'KCET',
    'GUJCET',
    'BCECE',
    'COMEDK',
  ],
  'Medical Entrance': [
    'NEET UG',
    'NEET PG',
    'AIIMS',
    'JIPMER',
    'NEET MDS',
    'FMGE',
    'INI-CET',
  ],
  'Law Entrance': [
    'CLAT',
    'AILET',
    'LSAT India',
    'MH CET Law',
    'DU LLB Entrance',
  ],
  'UPSC & IAS': [
    'UPSC Civil Services (IAS/IPS/IFS)',
    'UPSC CAPF',
    'UPSC NDA',
    'UPSC CDS',
    'UPSC IES/ESE',
    'IFoS',
    'RBI Grade B',
    'SEBI Grade A',
    'NABARD Grade A',
  ],
  'SSC & Railways': [
    'SSC CGL',
    'SSC CHSL',
    'SSC MTS',
    'SSC GD Constable',
    'SSC CPO',
    'SSC JE',
    'SSC Steno',
    'RRB NTPC',
    'RRB Group D',
    'RRB JE',
    'RRB ALP',
    'Indian Post GDS',
    'EPFO SSA',
  ],
  Banking: [
    'IBPS PO',
    'IBPS Clerk',
    'IBPS RRB PO',
    'IBPS RRB Clerk',
    'IBPS SO',
    'SBI PO',
    'SBI Clerk',
    'SBI SO',
    'RBI Assistant',
    'LIC AAO',
    'LIC ADO',
    'NIACL AO',
    'NICL AO',
  ],
  'Defence & Police': [
    'Indian Army',
    'Indian Navy',
    'Indian Air Force Agniveer',
    'CRPF',
    'BSF',
    'CISF',
    'ITBP',
    'Delhi Police',
    'UP Police',
    'Rajasthan Police',
    'Maharashtra Police',
    'NDA',
    'CDS',
    'Coast Guard',
    'Agniveer',
  ],
  'State Govt Jobs': [
    'State PSC (BPSC, MPPSC, UPPSC, RPSC, MPSC, TNPSC, KPSC, APPSC, TSPSC, OPSC, JPSC, GPSC, CGPSC, UKPSC)',
    'State Patwari/Lekhpal',
    'State Forest Guard',
    'State Fire Brigade',
    'State Homeguard',
    'State NHM Worker',
    'CTET',
    'STET',
    'Super TET',
    'Gram Panchayat Officer',
    'Anganwadi Worker',
    'Ward Boy/Attender',
    'Peon/Chaprasi/Group D',
  ],
  'Certifications & Skills': [
    'AWS Cloud',
    'Google Cloud',
    'Microsoft Azure',
    'Cisco CCNA',
    'PMP',
    'Google Analytics',
    'Meta Marketing',
    'HubSpot',
    'Salesforce',
    'CFA Level 1',
    'FRM',
    'ACCA',
    'Data Science',
    'Machine Learning',
    'Full Stack Web Dev',
    'UI/UX Design',
    'Digital Marketing',
    'Graphic Design',
    'Video Editing',
    'Content Writing',
    'Photography',
    'Yoga Instructor',
    'Tally ERP',
    'MS Office',
    'AutoCAD',
  ],
  'Language Exams': [
    'IELTS',
    'TOEFL',
    'PTE',
    'GMAT',
    'GRE',
    'SAT',
    'DELF French',
    'Goethe German',
    'JLPT Japanese',
    'HSK Chinese',
    'DELE Spanish',
  ],
  'MBA Entrance': [
    'CAT',
    'XAT',
    'SNAP',
    'NMAT',
    'IIFT',
    'MAT',
    'CMAT',
    'ATMA',
    'TISSNET',
    'MICAT',
    'IPM IIM Integrated',
  ],
  'Design & Architecture': [
    'NID Entrance',
    'NIFT Entrance',
    'CEED',
    'UCEED',
    'NATA',
    'Pearl Academy',
    'AIEED',
  ],
  'CUET & University': [
    'CUET UG',
    'CUET PG',
    'DUJAT',
    'BHU Entrance',
    'Jamia Entrance',
    'TISS Entrance',
  ],
};

export const SUBJECT_CATEGORIES = Object.keys(SUBJECT_CATALOG);

export const ALL_SUBJECT_OPTIONS = SUBJECT_CATEGORIES.flatMap((category) =>
  SUBJECT_CATALOG[category].map((label) => ({ label, category }))
);
